Style core element
zieeco/book-store-app pull request #4
Opened 2022-03-04 21:31 UTC by zieeco

In this milestone, I styled the app following the design and also made it responsive on mobile and desktop

2022-03-04 22:08 UTC, Cathella requested changes
## 🟡 Status: Changes Required 🛑

### Hi @zieeco 👋🏻, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## To Highlight 👏🏻

✅ No linter errors.
✅ You used correct Github Flow.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-04 22:08 UTC, Cathella commented on src/components/books/bookInfo.js
>  import { useDispatch } from 'react-redux';
- [ ] Kindly remove all commented out lines of code from the project. This helps in maintaining code readability

2022-03-04 22:08 UTC, Cathella commented on src/pages.css
> +}
Overall, you have done a beautiful job in styling this project according to the provided design. You just need to make a few changes to make perfect.

| Project Design | Zeplin Design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/4247740/156847775-b5490a9d-7d6f-4cd9-9fdb-2c9f28e8f04d.png) | ![bookstore](https://user-images.githubusercontent.com/4247740/156848007-3aa8ec93-bf2f-4211-8e17-aac7b7ffe788.png) |

- [ ] On comparing both designs, I think the shadow on the book component is unnecessary and can be removed
- [ ] Also the  form background is not meant to be white as seen in the original design.

2022-03-05 06:52 UTC, Rustamxon7 approved these changes
## HELLO @zieeco 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉, 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-03-05 06:53 UTC, merged